# Generated by Django 5.0 on 2023-12-25 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriptiolns',
            new_name='descriptions',
        ),
    ]
